config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tanks#index'
  resources :tanks do
    resources :treatments
    resources :transfers
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tank.rb
class Tank < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :treatments, dependent: :destroy
  has_many :transfers, dependent: :destroy

  def volume
    transfers.sum(:quantity)
  end
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :tank
  validates :quantity, :tank, presence: true
  validates :quantity, numericality: { greater_than: 0 }
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  belongs_to :tank
  validates :product, :tank, :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tanks_controller.rb
class TanksController < ApplicationController
  def index
    @tanks = Tank.all
  end

  def new
    @tank = Tank.new
  end

  def create
    @tank = Tank.new(tank_params)
    @tank.save!
    redirect_to root_path
  end

  def show
    find_tank
    @treatments = @tank.treatments
    @transfers = @tank.transfers
  end

  private

  def tank_params
    params.require(:tank).permit(:name)
  end

  def find_tank
    @tank = Tank.find(params[:id])
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  def new
    find_tank
    @transfer = Transfer.new
  end

  def create
    find_tank
    transfer = @tank.transfers.build(transfer_params)
    transfer.save!
    redirect_to tank_path(@tank)
  end


  private

  def find_tank
    @tank = Tank.find(params[:tank_id])
  end

  def transfer_params
    params.require(:transfer).permit(:quantity)
  end
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController

  def new
    find_tank
    @treatment = Treatment.new
  end

  def create
    find_tank
    treatment = @tank.treatments.build(treatment_params)
    treatment.save!
    redirect_to tank_path(@tank)
  end

  private

  def find_tank
    @tank = Tank.find(params[:tank_id])
  end

  def treatment_params
    params.require(:treatment).permit(:name, :product, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tank_helper.rb
module TankHelper
end

app/helpers/transfers_helper.rb
module TransfersHelper
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExoEkylibre</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tanks/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>Les cuves</h1>
      <%= link_to("Ajouter une cuve", new_tank_path) %>
      <div class="">
        <% @tanks.each do |tank| %>
          <div class="">
            <%= link_to(tank.name, tank_path(tank)) %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tanks/new.html.erb
<div class="">
  Ajouter une cuve
  <%= render "tanks/partials/form"  %>
</div>

app/views/tanks/partials/_form.html.erb
<div class="">
  <%= simple_form_for(@tank) do |f| %>
    <%= f.input :name %>
    <%= f.submit %>
  <% end %>
</div>

app/views/tanks/show.html.erb
<div class="">
  <h1><%= @tank.name %></h1>
  Volume : <strong><%= @tank.volume  %></strong>
  <div class="treatments">
    <%= link_to("Ajouter un traitement", new_tank_treatment_path(@tank))  %>
    <% @treatments.each do |treatment| %>
      <h3><%= treatment.name %></h3>
      <strong><%= treatment.product %></strong>
      <p><%= treatment.comment %></p>
    <% end %>
  </div>
  <div class="transfers">
    <%= link_to("Créer un transfert", new_tank_transfer_path(@tank))  %>
    <div class="">
      <ul>
        <% @transfers.each do |transfer| %>
          <li><%= transfer.quantity %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/transfers/new.html.erb
<div class="">
  <%= simple_form_for(@transfer, url: tank_transfers_path(@tank)) do |f| %>
    <%= f.input :quantity  %>
    <%= f.submit  %>
  <% end %>
</div>

app/views/treatments/new.html.erb
<%= simple_form_for(@treatment, url: tank_treatments_path(@tank)) do |f| %>
  <%= f.input :name  %>
  <%= f.input :product %>
  <%= f.input :comment, as: :text %>
  <%= f.submit %>
<% end %>